parser: babel-eslint

env:
    browser: true

parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react

rules:
    no-confusing-arrow: 2
    no-mixed-spaces-and-tabs: 2
    no-multiple-empty-lines: [2, {max: 1, maxEOF: 0, maxBOF: 0}]
    no-trailing-spaces: 2
    no-whitespace-before-property: 2
    object-curly-spacing: [2, always]
    prefer-arrow-callback: 2
    prefer-template: 2
    quotes: [2, single]
    semi: [2, always]
    space-before-blocks: 2

    react/jsx-uses-vars: 2
    react/jsx-no-duplicate-props: 2
    react/prop-types: [2, { ignore: [children] }]
    react/prefer-stateless-function: 2
    react/class-methods-use-this: 0
