parser: babel-eslint

env:
    browser: true

parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true

plugins:
    - react

rules:
    no-confusing-arrow: 2
    no-mixed-spaces-and-tabs: 2
    no-multiple-empty-lines: [1, {max: 1, maxEOF: 0, maxBOF: 0}]
    no-trailing-spaces: 1
    no-whitespace-before-property: 1
    object-curly-spacing: [1, always]
    prefer-arrow-callback: 2
    prefer-template: 1
    quotes: [1, single]
    semi: [1, always]
    space-before-blocks: 1
    template-curly-spacing: [1, always]

    react/jsx-uses-vars: 1
    react/jsx-no-duplicate-props: 2
    react/prop-types: [1, { ignore: [children] }]
    react/prefer-stateless-function: 2
    react/class-methods-use-this: 0
